In [2]:
import pandas as pd

df = pd.read_csv("/Users/anshulmehra/WEB_SCRAPING/data/Redmi 10.csv")
df.drop('Unnamed: 0',axis=1,inplace=True)
df

,Product,Name,Rating,CommentHead,Comment
0,redmi 10,Flipkart customer,4,Pretty good,"After 14 days from buying this product, I gav..."
1,redmi 10,Aakash biswas,5,Mind-blowing purchase,â€¢ Value for money Product.â€¢ Good Battery Life....
2,redmi 10,Yogesh raghav,3,Does the job,50mp based on 2005 times like 2 maga pixel ðŸ˜‚ðŸ˜‚ðŸ˜‚...
3,redmi 10,Sumit banerjee,3,Decent product,Extremely Big phone with average build quality...
4,redmi 10,Dhamchelam dukpa,5,Terrific,"Thank u so much flick karte ðŸ˜Š value of money, ..."
5,redmi 10,Basudeb sahoo,5,Awesome,it's best phone is 4gTo good phone all need to...
6,redmi 10,Nishant katalkar,5,Excellent,Camera quality good . nice product with this r...
7,redmi 10,Flipkart customer,5,Simply awesome,Mobile was awsm good battery good display But ...
8,redmi 10,Pravin awate,4,Bad quality,Camera is very poor. Pictures taken with its 5...
9,redmi 10,Dipankar roy,4,Value-for-money,"Camera quality could be better, there is only ..."

In [3]:
dff = pd.read_csv("/Users/anshulmehra/WEB_SCRAPING/data/Iphone 14.csv")
dff.drop('Unnamed: 0',axis=1,inplace=True)
dff

,Product,Name,Rating,CommentHead,Comment
0,iphone 14,Rahul prasad,5,Fabulous!,Best smart phone under this price range compar...
1,iphone 14,Flipkart customer,5,Great product,Damn such a great phone. Camera is really good...
2,iphone 14,Flipkart customer,5,Best in the market!,"Excellent smart phone, Good battery backup and..."
3,iphone 14,Feecon behera,5,Must buy!,Just awesome!!I switch to iPhone 14 from iPhon...
4,iphone 14,Samaresh tikader,5,Fabulous!,Happy to have iPhone 14. Wonderful phone speci...
5,iphone 14,Kunal dhamija,5,Classy product,Totally in love with my new iphone 14. Battery...
6,iphone 14,Manish choudhary,5,Perfect product!,Amazing deviceI switch to iPhone 14 from iPhon...
7,iphone 14,Ashutosh kumar,5,Classy product,Great phone with great capabilities ðŸ”¥Excellent...
8,iphone 14,Afzal khan,5,Fabulous!,Best one. Have not used a better mobile than t...
9,iphone 14,Sunder singh,5,Highly recommended,I am so happy to have first time i phone 14. M...